import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

data = github_raw_url = 'https://raw.githubusercontent.com/mauriceoboya/Machine-learning/main/unsupervised_models/Analytics_data.csv'
data = pd.read_csv(data)

columns = ["Date", "Agent name", "Response", "uid", "Converted?", 
           "average payment delay before weekly", "revenue per day before weekly", "revenue per day after weekly"]

df = pd.DataFrame(data, columns=columns)

# Convert the 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])
df['Date'].dropna(inplace=True)
df['Date'] = df['Date'].astype('datetime64[ns]')


# Calculate additional metrics
df['Revenue per day standard'] = 1500 / 30
df['Revenue per day with delay'] = df['revenue per day before weekly'] / (30 + df['average payment delay before weekly'])

# Streamlit app
st.title('Poa! Internet Subscription Pilot Analysis')
st.subheader('Poa Pilot project Data')
st.dataframe(df.head())

#  Analyze customer conversion, reachability, and agent performance
st.header('Customer Conversion, Reachability, and Agent Performance')

# Conversion analysis
converted_customers = df[df['Converted?'] == 'Yes']
conversion_rate = len(converted_customers) / len(df) * 100

st.subheader('Conversion Analysis')
st.write(f"Total Number of Customers: {len(df)}")
st.write(f"Number of Converted Customers: {len(converted_customers)}")
st.write(f"Conversion Rate: {conversion_rate:.2f}%")

# Conversion trends over time
st.line_chart(df.set_index('Date')['Converted?'].eq('Yes').resample('M').mean())

# Reachability analysis by day of week
st.subheader('Reachability Analysis by Day of Week')
df['Day of Week'] = df['Date'].dt.day_name()
reachability_by_day = df.groupby('Day of Week')['Response'].value_counts().unstack().fillna(0)
st.bar_chart(reachability_by_day)

# Agent performance analysis
st.subheader('Agent Performance Analysis')
agent_performance = df.groupby('Agent name')['Converted?'].value_counts().unstack().fillna(0)
st.bar_chart(agent_performance)

# Findings
st.subheader('Findings')
st.write("1. **Conversion Rate Trends:** The conversion rate has been fluctuating over time. Further investigation is needed to understand the factors influencing these fluctuations.")
st.write("2. **Reachability Insights:** Customers are most reachable on specific days of the week. Consider optimizing the calling schedule based on this information.")
st.write("3. **Agent Performance:** Some agents show higher conversion rates than others. Identify and share best practices among agents for better overall performance.")


st.header('Other Metrics')
# Revenue analysis
st.subheader('Revenue Analysis')

# Revenue per day comparison
fig1 = px.bar(df, x="Agent name", y="revenue per day after weekly", title="Total Revenue by Agent")
st.plotly_chart(fig1)

# Payment delay distribution using Plotly Express
total_revenue = df.groupby("Agent name")["revenue per day after weekly"].sum().reset_index()
fig3 = px.bar(total_revenue, x="Agent name", y="revenue per day after weekly", title="Total Revenue by Agent")
st.plotly_chart(fig3)
st.subheader('Findings')
st.write("The 'Total Revenue by Agent' plot shows the total revenue generated by each agent. Agents with highest bar (Allan Mutuota) contribute more to the overall revenue. This can be a key metric to identify top-performing agents in terms of revenue generation.")

# Question 3: Data Story and Recommendations
st.header('Data Summary and Recommendations')

# Summary statistics
summary_stats = df.describe()
st.write(summary_stats)

# Recommendations
st.subheader('Recommendations')
st.write("- Continue offering flexible plans to customers with 1 to 7 days average payment delay.")
st.write("- Investigate reasons for low conversion rates on specific days.")
st.write("- Recognize and reward high-performing agents.")

# Explore further
st.subheader('Explore Further')
st.write("- Conduct customer surveys to understand reasons for plan declines.")
st.write("- Evaluate the impact of the periodic billing pilot on overall customer satisfaction.")





